--FINAL PROJECT DATABASE
--PROJECT NAME: PERSONAL BLOG

USE master;
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name = 'myBlogProject')
DROP DATABASE myBlogProject;
GO

CREATE DATABASE myBlogProject
GO

USE myBlogProject;
GO

CREATE TABLE Post
(
	PostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	Title NVARCHAR(255),
	PostBody NVARCHAR(MAX),
	Author NVARCHAR(255),
	PostDate DATETIME
);

CREATE TABLE Comment
(
	CommentID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	UserName NVARCHAR(255),
	CommentBody NVARCHAR(MAX),
	CommentDate DATETIME,

	PostID INT NOT NULL, --FK
	FOREIGN KEY(PostID) REFERENCES Post(PostID) ON DELETE CASCADE
);

CREATE TABLE Admin
(
	AdminID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	AdminName NVARCHAR(50),
	AdminPassword NVARCHAR(255)
);

