--FINAL PROJECT DATABASE
--PROJECT NAME: PERSONAL BLOG

USE master;
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'myBlog')
DROP DATABASE myBlog;
GO

CREATE DATABASE myBlog
GO

USE myBlog;
GO

CREATE TABLE Post
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	TITLE NVARCHAR(255),
	POST_BODY NVARCHAR(MAX),
	POST_AUTHOR NVARCHAR(255),
	P_DATE_TIME DATETIME
);

CREATE TABLE Comments
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	USERNAME NVARCHAR(255),
	USER_EMAIL NVARCHAR(255),
	COMMENT_BODY NVARCHAR(MAX),
	C_DATE_TIME DATETIME,

	C_POST_ID INT NOT NULL, --FK
	FOREIGN KEY(C_POST_ID) REFERENCES Post(ID) ON DELETE CASCADE
);

CREATE TABLE Admins
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	ADMIN_NAME NVARCHAR(50),
	ADMIN_EMAIL NVARCHAR(50),
	ADMIN_PASSWORD NVARCHAR(255)
);

