--FINAL PROJECT DATABASE
--PROJECT NAME: PERSONAL BLOG

USE master;
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'myBlogProject')
DROP DATABASE myBlog;
GO

CREATE DATABASE myBlogProject
GO

USE myBlogProject;
GO

CREATE TABLE Posts
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	TITLE NVARCHAR(255),
	POST_BODY NVARCHAR(MAX),
	POST_AUTHOR NVARCHAR(255),
	P_DATE_TIME DATETIME
);

CREATE TABLE Tags
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	TAG_NAME NVARCHAR(MAX)
);

CREATE TABLE PostTags
(
	TAG_ID INT NOT NULL,
	POST_ID INT NOT NULL,
	
	FOREIGN KEY(TAG_ID) REFERENCES dbo.Tags(ID) ON DELETE CASCADE,
	FOREIGN KEY(POST_ID) REFERENCES dbo.Posts(ID) ON DELETE CASCADE
);

CREATE TABLE Comments
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	USERNAME NVARCHAR(255),
	USER_EMAIL NVARCHAR(255),
	COMMENT_BODY NVARCHAR(MAX),
	C_DATE_TIME DATETIME,

	C_POST_ID INT NOT NULL, --FK
	FOREIGN KEY(C_POST_ID) REFERENCES Posts(ID) ON DELETE CASCADE
);

CREATE TABLE Admins
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, --PK
	ADMIN_NAME NVARCHAR(50),
	ADMIN_EMAIL NVARCHAR(50),
	ADMIN_PASSWORD NVARCHAR(255)
);

