using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Data.Entity;
using Blog.Models;

namespace Blog.DAL
{
    public class BlogInitializer : DropCreateDatabaseIfModelChanges<BlogDBContext>
    {
        protected override void Seed(BlogDBContext context)
        { 
            var posts = new List<Posts>
            {
                new Posts {Title="Title1",Author="Author1",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title2",Author="Author2",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title3",Author="Author3",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title4",Author="Author4",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title5",Author="Author5",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title6",Author="Author6",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title7",Author="Author7",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title8",Author="Author8",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title9",Author="Author9",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
                new Posts {Title="Title10",Author="Author10",PostBody="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum, lorem vel tempor facilisis, ipsum sem scelerisque dolor, ultricies varius felis tortor vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi gravida neque consequat pellentesque imperdiet. Vestibulum urna magna, iaculis in consequat vel, accumsan quis arcu. Nam sed ipsum vel lectus vestibulum accumsan. Integer porta augue ac turpis imperdiet, in consequat massa vehicula. Sed sit amet dolor scelerisque massa cursus hendrerit sit amet at magna. Donec rutrum ligula eu erat sollicitudin varius. Sed sagittis varius porta. Sed mollis sed ipsum ac gravida. Curabitur faucibus tortor in magna iaculis mattis. Fusce finibus dolor quis orci dictum accumsan. Etiam sit amet diam quis eros posuere auctor vel ac lacus. Nullam eget lorem nulla. Sed quis nibh id lorem vehicula rutrum at vel massa.",PostDate=DateTime.Now,/*Tags = new List<Tags>()*/ },
            };
            posts.ForEach(p => context.Post.Add(p));
            context.SaveChanges();
        }
    }
}